Repository upbound/universal-crossplane, pull requests merged in 2021-06, with the labels that each got.

#124 [release-1.2] Backport OLM metadata and README.md changes
  Makefile
  README.md
  cluster/charts/universal-crossplane/Chart.yaml
  cluster/olm/.gitignore
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurations.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-browse.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.serviceaccount.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_allowed-provider-permissions.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/rbac-manager.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-tls.secret.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.service.yaml
  cluster/olm/bundle/manifests/upbound-agent.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.role.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.serviceaccount.yaml
  cluster/olm/bundle/manifests/uxp-ca.secret.yaml
  cluster/olm/bundle/manifests/xgql-tls.secret.yaml
  cluster/olm/bundle/manifests/xgql.service.yaml
  cluster/olm/bundle/manifests/xgql.serviceaccount.yaml
Labels: cla-signed

#126 olm: update with more metadata
  cluster/olm/README.md
  cluster/olm/clusterserviceversion.yaml.tmpl
Labels: backport release-1.2, cla-signed, size/S

#127 [backport 1.2] olm: update with more metadata
  cluster/olm/README.md
  cluster/olm/clusterserviceversion.yaml.tmpl
Labels: cla-signed, size/M

#129 Deploy xgql v0.1.3
  Makefile
Labels: backport release-1.2, cla-signed, size/XS

#128 Propagate handy GitHub workflows
  .github/workflows/backport.yml
  .github/workflows/commands.yml
Labels: cla-signed, size/M

#131 [release-1.2] Update Crossplane to v1.2.2
  Makefile
Labels: cla-signed, size/XS

#135 Expose UXP version in versions ConfigMap
  cluster/charts/universal-crossplane/templates/bootstrapper/versions-configmap.yaml
Labels: backport release-1.2, cla-signed, size/XS

#139 Add --insecure flag to agent
  Makefile
  cluster/local/config/universal-crossplane/value-overrides.yaml.tmpl
  cmd/upbound-agent/main.go
  internal/clients/upbound/upbound.go
  internal/clients/upbound/upbound_test.go
  internal/upboundagent/proxy.go
Labels: cla-signed, size/M

#132 Update Crossplane to v1.3.0-rc.0
  Makefile
Labels: cla-signed, size/XS

#138 Build and publish OLM bundle
  Makefile
  cluster/olm/README.md
Labels: backport release-1.2, cla-signed, size/M

#140 More examples and readme to OLM bundle
  Makefile
  README.md
  cluster/olm/clusterserviceversion.yaml.tmpl
Labels: backport release-1.2, cla-signed, size/L

#143 Update olm-bundle to v0.5.1
  Makefile
  cluster/olm/bundle/Dockerfile
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurations.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-browse.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.serviceaccount.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_allowed-provider-permissions.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/rbac-manager.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-tls.secret.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.service.yaml
  cluster/olm/bundle/manifests/upbound-agent.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.role.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.serviceaccount.yaml
  cluster/olm/bundle/manifests/uxp-ca.secret.yaml
  cluster/olm/bundle/manifests/xgql-tls.secret.yaml
  cluster/olm/bundle/manifests/xgql.service.yaml
  cluster/olm/bundle/manifests/xgql.serviceaccount.yaml
  cluster/olm/bundle/metadata/annotations.yaml
Labels: backport release-1.2, cla-signed

#147 Rename remaining gateways as agent
  cmd/upbound-agent/main.go
  internal/clients/upbound/mocks/upbound.go
  internal/clients/upbound/upbound.go
  internal/clients/upbound/upbound_test.go
  internal/controllers/tlssecrets/reconciler.go
  internal/controllers/tlssecrets/reconciler_test.go
Labels: backport release-1.2, cla-signed, size/M

#148 [release 1.2] Rename remaining gateways as agent
  cmd/upbound-agent/main.go
  internal/clients/upbound/mocks/upbound.go
  internal/clients/upbound/upbound.go
  internal/clients/upbound/upbound_test.go
  internal/controllers/tlssecrets/reconciler.go
  internal/controllers/tlssecrets/reconciler_test.go
Labels: cla-signed, size/M

#149 Bump xgql to v0.1.4
  Makefile
Labels: backport release-1.2, cla-signed, size/XS

#153 [release-1.2] Update Crossplane to v1.2.3
  Makefile
Labels: cla-signed, size/XS

#154 olm: add necessary entries to annotations for RedHat certification
  Makefile
  cluster/olm/annotations.yaml.tmpl
  cluster/olm/bundle/Dockerfile
  cluster/olm/bundle/metadata/annotations.yaml
Labels: backport release-1.2, cla-signed, size/M

#146 Bootstrapper manages Upbound agent deployment and re-enables healthcheks
  cluster/charts/universal-crossplane/templates/bootstrapper/deployment.yaml
  cluster/charts/universal-crossplane/templates/bootstrapper/role.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/_deployment-spec.tpl
  cluster/charts/universal-crossplane/templates/upbound-agent/deployment.yaml
  cluster/local/config/validation/validate.sh
  cluster/olm/.gitignore
  cluster/olm/bundle/manifests/upbound-bootstrapper.role.yaml
  cmd/bootstrapper/main.go
  cmd/upbound-agent/main.go
  go.mod
  internal/controllers/upboundagent/reconciler.go
  internal/controllers/upboundagent/reconciler_test.go
Labels: backport release-1.2, cla-signed, size/XL

#152 Release process guide
  CONTRIBUTING.md
  README.md
  docs/developer-guide.md
Labels: cla-signed, size/L

#158 Do not suggest usage of upbound org in olm testing
  cluster/olm/README.md
Labels: size/XS

#159 Make promotion default the stable channel
  .github/workflows/promote.yml
Labels: size/XS

#160 Add configuration install manifest for getting started
  docs/getting-started/install.yaml
Labels: size/XS
