Repository upbound/universal-crossplane, pull requests merged in 2021-05, with the labels that each got.

#85 Remove credentials for accessing private dependencies
  .github/workflows/ci.yml
  .github/workflows/pushvalidation.yml
Labels: cla-signed

#97 Update readme and helm chart.yaml
  README.md
  cluster/charts/universal-crossplane/Chart.yaml
  cluster/olm/clusterserviceversion.yaml.tmpl
Labels: cla-signed

#99 Add getting started doc snippets
  docs/getting-started/claim.yaml
  docs/getting-started/configuration/composition.yaml
  docs/getting-started/configuration/crossplane.yaml
  docs/getting-started/configuration/definition.yaml
  docs/getting-started/providerconfig.yaml
Labels: cla-signed

#100 [localdev] Only delete Control plane if token provided
  cluster/local/config/validation/deploy.sh
Labels: cla-signed

#98 readme: add homebrew install instructions for up CLI
  README.md
Labels: cla-signed

#101 Point to provider-aws on upbound registry for getting started
  docs/getting-started/configuration/crossplane.yaml
Labels: cla-signed

#105 Update olm
  Makefile
  cluster/olm/.gitignore
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurations.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-browse.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.serviceaccount.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_allowed-provider-permissions.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/rbac-manager.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-tls.secret.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.service.yaml
  cluster/olm/bundle/manifests/upbound-agent.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.role.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.serviceaccount.yaml
  cluster/olm/bundle/manifests/uxp-ca.secret.yaml
  cluster/olm/bundle/manifests/xgql-tls.secret.yaml
  cluster/olm/bundle/manifests/xgql.service.yaml
  cluster/olm/bundle/manifests/xgql.serviceaccount.yaml
Labels: cla-signed

#106 Use stable up version for testing
  Makefile
Labels: cla-signed

#103 Update UXP documentation link in the readme
  README.md
Labels: cla-signed, size/XS

#114 Sync values.yaml.tmpl with Crossplane v1.2.1
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: cla-signed, size/M

#117 [release-1.2] Sync values.yaml.tmpl with Crossplane v1.2.1
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: cla-signed, size/M

#120 [release-1.2] helm: update logo URL in Chart.yaml
  cluster/charts/universal-crossplane/Chart.yaml
Labels: cla-signed, size/XS

#121 Add backport GitHub Action
  .github/workflows/backport.yml
Labels: cla-signed, size/S
