Repository upbound/universal-crossplane, pull requests merged in 2021-09, with the labels that each got.

#178 Use Upbound maintained Crossplane
  Makefile
  cluster/charts/universal-crossplane/values.yaml.tmpl
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_controllerconfigs.yaml
  cluster/crds/pkg.crossplane.io_locks.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/local/config/universal-crossplane/config.env
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
Labels: size/XXL

#175 Update versioning doc: always start with -up.1
  VERSIONING.md
  docs/media/versioning.png
Labels: size/S

#179 Use Upbound Crossplane version v1.4.0-up.1
  Makefile
Labels: size/XS

#180 Update release process for Upbound maintained Crossplane
  CONTRIBUTING.md
Labels: size/M

#183 Getting started configuration should work with rc versions
  docs/getting-started/configuration/crossplane.yaml
Labels: size/XS

#185 olm: remove runAsGroup and runAsUser from pods
  Makefile
  cluster/olm/README.md
Labels: size/S, backport release-1.4, backport release-1.3

#189 Add support for passing extra env vars for all components
  cluster/charts/universal-crossplane/templates/bootstrapper/deployment.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/_deployment-spec.tpl
  cluster/charts/universal-crossplane/templates/xgql/deployment.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: size/M

#190 [release-1.4] Add support for passing extra env vars for all components
  cluster/charts/universal-crossplane/templates/bootstrapper/deployment.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/_deployment-spec.tpl
  cluster/charts/universal-crossplane/templates/xgql/deployment.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: size/M

#191 [release-1.3] Add support for passing extra env vars for all components
  cluster/charts/universal-crossplane/templates/bootstrapper/deployment.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/_deployment-spec.tpl
  cluster/charts/universal-crossplane/templates/xgql/deployment.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: size/M
