Repository upbound/universal-crossplane, pull requests merged in 2021-11, with the labels that each got.

#198 readme: add release policy
  README.md
Labels: size/S

#203 crossplane: update to v1.5.1-up.1
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-deployment.yaml
  cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_configurations.yaml
  cluster/crds/pkg.crossplane.io_controllerconfigs.yaml
  cluster/crds/pkg.crossplane.io_locks.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/crds/pkg.crossplane.io_providers.yaml
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurations.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
Labels: size/L

#206 Update values.yaml.tmpl in release-1.5
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: size/XS

#200 Bump xgql to v0.1.5
  Makefile
Labels: size/XS, backport release-1.2, backport release-1.4, backport release-1.3

#204 crossplane: update to v1.4.3-up.1
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-deployment.yaml
Labels: size/XS

#205 crossplane: update to v1.3.3
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-deployment.yaml
Labels: size/XS

#202 crossplane: update main branch to v1.6.0-rc.0.up.1.72.g4f292d31
  Makefile
  cluster/charts/universal-crossplane/templates/_helpers.tpl
  cluster/charts/universal-crossplane/templates/crossplane/_helpers.tpl
  cluster/charts/universal-crossplane/templates/crossplane/clusterrole.yaml
  cluster/charts/universal-crossplane/templates/crossplane/clusterrolebinding.yaml
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-allowed-provider-permissions.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-clusterrole.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-clusterrolebinding.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-deployment.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-managed-clusterroles.yaml
  cluster/charts/universal-crossplane/templates/crossplane/rbac-manager-serviceaccount.yaml
  cluster/charts/universal-crossplane/templates/crossplane/serviceaccount.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/clusterrolebindings-managed.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/clusterroles-managed.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
  cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_configurations.yaml
  cluster/crds/pkg.crossplane.io_controllerconfigs.yaml
  cluster/crds/pkg.crossplane.io_locks.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/crds/pkg.crossplane.io_providers.yaml
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurations.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-admin.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-browse.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane-rbac-manager.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane.serviceaccount.yaml
  cluster/olm/bundle/manifests/crossplane_allowed-provider-permissions.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/rbac-manager.serviceaccount.yaml
Labels: size/XL

#181 Update publishing to marketplaces section in Docs
  CONTRIBUTING.md
Labels: size/XS
