Repository upbound/universal-crossplane, pull requests merged in 2022-09, with the labels that each got.

#283 Drop up attach commands from README.md
  README.md
  docs/media/uxp-in-ubc.png
Labels: size/S

#288 Duplicated registryCaBundleConfig in values.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: size/XS

#293 [release-1.9] Pin Crossplane version to v1.9.1-up.1
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/clusterrole.yaml
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
Labels: size/S

#291 [release-1.7] Pin Crossplane version to v1.7.3-up.1
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/clusterrole.yaml
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
Labels: size/M

#292 [release-1.8] Pin Crossplane version to v1.8.2-up.1
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/clusterrole.yaml
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
Labels: size/S

#290 Update NOTES.txt to exclude deprecated commands and use new CTA
  cluster/charts/universal-crossplane/templates/NOTES.txt
Labels: size/S, backport release-1.8, backport release-1.7, backport release-1.9

#297 Use HTTPS instead of SSH for build submodule
  .gitmodules
Labels: size/XS

#300 Remove agent and related code
  Makefile
  VERSIONING.md
  cluster/charts/universal-crossplane/templates/bootstrapper/deployment.yaml
  cluster/charts/universal-crossplane/templates/bootstrapper/role.yaml
  cluster/charts/universal-crossplane/templates/bootstrapper/versions-configmap.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/_deployment-spec.tpl
  cluster/charts/universal-crossplane/templates/upbound-agent/_helpers.tpl
  cluster/charts/universal-crossplane/templates/upbound-agent/clusterrole.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/clusterrolebindings-managed.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/clusterrolebindings.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/clusterroles-managed.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/control-plane-token-secret.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/role.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/service.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/serviceaccount.yaml
  cluster/charts/universal-crossplane/templates/upbound-agent/tls-secret.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
  cluster/images/upbound-agent/Dockerfile
  cluster/images/upbound-agent/Makefile
  cluster/olm/bundle/manifests/crossplane-edit.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane-view.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-edit.clusterrole.yaml
  cluster/olm/bundle/manifests/crossplane_aggregate-to-view.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent-impersonator.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-secret.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent-tls.secret.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.role.yaml
  cluster/olm/bundle/manifests/upbound-agent-uxp-config.rolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrole.yaml
  cluster/olm/bundle/manifests/upbound-agent.clusterrolebinding.yaml
  cluster/olm/bundle/manifests/upbound-agent.service.yaml
  cluster/olm/bundle/manifests/upbound-agent.serviceaccount.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.role.yaml
  cmd/bootstrapper/main.go
  cmd/upbound-agent/main.go
  cmd/upbound-agent/main_test.go
  go.mod
  go.sum
  internal/clients/upbound/mocks/upbound.go
  internal/clients/upbound/upbound.go
  internal/clients/upbound/upbound_test.go
  internal/controllers/billing/aws/aws_test.go
  internal/controllers/tlssecrets/reconciler.go
  internal/controllers/tlssecrets/reconciler_test.go
  internal/controllers/upboundagent/reconciler.go
  internal/controllers/upboundagent/reconciler_test.go
  internal/upboundagent/config.go
  internal/upboundagent/internal/upboundapi.go
  internal/upboundagent/natsconn.go
  internal/upboundagent/natsconn_test.go
  internal/upboundagent/proxy.go
  internal/upboundagent/proxy_test.go
Labels: size/XXL
