Repository upbound/universal-crossplane, pull requests merged in 2022-07, with the labels that each got.

#255 [release-1.6] Update Crossplane version to v1.6.7-up.2
  Makefile
Labels: size/XS

#256 Add AWS_DEFAULT_REGION in CI
  .github/workflows/ci.yml
  .github/workflows/promote.yml
Labels: size/XS, backport release-1.6, backport release-1.8, backport release-1.7

#263 Update install.yaml to use correct FQDN
  docs/getting-started/install.yaml
Labels: size/XS

#265 Bump RBAC manager memory requests and limits
  cluster/charts/universal-crossplane/values.yaml.tmpl
Labels: size/XS, backport release-1.8, backport release-1.7
