Repository upbound/universal-crossplane, pull requests merged in 2022-08, with the labels that each got.

#272 update for v1.9.0-up.1 release
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_controllerconfigs.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
Labels: size/L

#273 [release-1.9] Update Crossplane to v1.9.0-up.2
  Makefile
Labels: size/XS

#281 Release 1.9.0-up.3
  Makefile
  cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/crds/pkg.crossplane.io_providers.yaml
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
Labels: size/M
