Repository upbound/universal-crossplane, pull requests merged in 2022-02, with the labels that each got.

#221 Make upbound-agent owned by versions ConfigMap
  cluster/charts/universal-crossplane/templates/bootstrapper/role.yaml
  cluster/olm/bundle/manifests/upbound-bootstrapper.role.yaml
  internal/controllers/upboundagent/reconciler.go
  internal/controllers/upboundagent/reconciler_test.go
Labels: size/L, backport release-1.6

#223 Fix hard coded provider in aws getting-started package
  docs/getting-started/configuration/crossplane.yaml
Labels: size/XS

#226 [release-1.5] Update nats-proxy to fix CVE-2022-24450
  go.mod
  go.sum
Labels: size/XS

#227 [release-1.4] Update nats-proxy to fix CVE-2022-24450
  go.mod
  go.sum
Labels: size/XS

#217 Document how to sync Upbound's Crossplane fork
  CONTRIBUTING.md
Labels: size/M

#228 Fix small typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#229 Update crossplane version to v1.6.3-up.1
  Makefile
  cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_configurations.yaml
  cluster/crds/pkg.crossplane.io_controllerconfigs.yaml
  cluster/crds/pkg.crossplane.io_locks.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/crds/pkg.crossplane.io_providers.yaml
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurations.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/controllerconfigs.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/locks.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/providers.pkg.crossplane.io.customresourcedefinition.yaml
Labels: size/L

#230 Update crossplane version to v1.5.2-up.1
  Makefile
Labels: size/XS

#231 Update crossplane version to v1.4.4-up.1
  Makefile
Labels: size/XS
