Repository upbound/universal-crossplane, pull requests merged in 2022-04, with the labels that each got.

#240 crossplane: update to v1.7.0
  Makefile
  cluster/charts/universal-crossplane/templates/crossplane/clusterrole.yaml
  cluster/charts/universal-crossplane/templates/crossplane/deployment.yaml
  cluster/charts/universal-crossplane/templates/crossplane/secret.yaml
  cluster/charts/universal-crossplane/templates/crossplane/service.yaml
  cluster/charts/universal-crossplane/values.yaml.tmpl
  cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/crds/secrets.crossplane.io_storeconfigs.yaml
  cluster/olm/bundle/manifests/compositeresourcedefinitions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositionrevisions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/compositions.apiextensions.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/configurationrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/crossplane_system_aggregate-to-crossplane.clusterrole.yaml
  cluster/olm/bundle/manifests/providerrevisions.pkg.crossplane.io.customresourcedefinition.yaml
  cluster/olm/bundle/manifests/storeconfigs.secrets.crossplane.io.customresourcedefinition.yaml
Labels: size/XL

#241 go.mod: update dependencies to address reported CVEs
  .github/workflows/ci.yml
  .github/workflows/pushvalidation.yml
  go.mod
  go.sum
Labels: size/S

#242 go.mod: update jwt libraries
  go.mod
  go.sum
  internal/upboundagent/natsconn.go
Labels: size/XS

#243 Update PostgreSQL engine version for UXP getting-started package
  docs/getting-started/configuration/composition.yaml
Labels: size/XS
